### PR TITLE
Implement FadeManager.hx

### PR DESCRIPTION
**Pull request by DillyzThe1**
Implement the previously planned [FadeManager.hx](https://github.com/impostor5875/Kolor-Kingdom/blob/main/source/FadeManager.hx) class.

Video of implementation:

https://user-images.githubusercontent.com/34419642/182006971-57facfbc-4073-4eb2-bb22-5f77376a3867.mp4

### CODE REVIEW

**Comment by DillyzThe1** [comment]
Example usage from source:
`FadeManager.fadeAndSwitchState(PlayState);`

**Comment by impostor5875** [comment]
NIIICE

you fixed the FadeManager thing and even added a basic KKState to automatically fade back out

**Comment by impostor5875** [comment]
definitely merging this

**Comment by DillyzThe1** [comment]
ok thanks

also if you swap the default to white it actually looks cool (or at least just put it for the menu)
but black is good for generic stuff

**Pull request merged**
